<?php declare(strict_types=1);

namespace TotalCRM\OzonApi\Service\V1;

use TotalCRM\OzonApi\Enum\TransactionType;
use TotalCRM\OzonApi\Exception\OzonApiException;
use TotalCRM\OzonApi\Service\AbstractService;
use TotalCRM\OzonApi\Utils\ArrayHelper;
use Throwable;

/**
 * Class ReportService
 * @package TotalCRM\OzonApi\Service\V1
 * @see https://cb-api.ozonru.me/apiref/en/#t-title_seller_reports
 */
class ReportService extends AbstractService
{
    /**
     * Returns a list of reports which were previously generated by Seller.
     *
     * @see https://cb-api.ozonru.me/apiref/en/#t-title_post_reportlist
     *
     * @param array $query
     * @return array|string
     * @throws Throwable
     * @throws OzonApiException
     */
    public function list(array $query)
    {
        $query = ArrayHelper::pick($query, ['page', 'page_size', 'report_type']);

        return $this->request('POST', '/v1/report/list', $query);
    }

    /**
     * Get report info by unique ID.
     *
     * @see https://cb-api.ozonru.me/apiref/en/#t-title_post_reportinfo
     *
     * @param string|null $code
     * @return array|string
     * @throws OzonApiException
     * @throws Throwable
     */
    public function info(string $code = null)
    {
        $query = array_filter(['code' => $code]);

        return $this->request('POST', '/v1/report/info', $query);
    }

    /**
     * Returns products reports, which is also available in Seller Center.
     *
     * @see https://cb-api.ozonru.me/apiref/en/#t-title_post_reportproducts
     *
     * @param array $query ['offer_id', 'search', 'sku', 'visibility']
     *
     * @return array
     * @throws OzonApiException
     * @throws Throwable
     */
    public function products(array $query = [])
    {
        $query = ArrayHelper::pick($query, ['offer_id', 'search', 'sku', 'visibility']);
        $query = array_filter($query);

        return $this->request('POST', '/v1/report/products/create', $query);
    }

    /**
     * Returns products reports, which is also available in Seller Center.
     *
     * @see https://cb-api.ozonru.me/apiref/en/#t-title_post_reporttransactions
     *
     * @param \DateTimeInterface $dateFrom
     * @param \DateTimeInterface $dateTo
     * @param string|null $search
     * @param string $transactionType
     * @return array|string
     * @throws OzonApiException
     * @throws Throwable
     */
    public function transaction(\DateTimeInterface $dateFrom, \DateTimeInterface $dateTo, string $search = null, string $transactionType = TransactionType::ALL)
    {
        $query = array_filter([
            'date_from'        => $dateFrom->format('Y-m-d'),
            'date_to'          => $dateTo->format('Y-m-d'),
            'search'           => $search,
            'transaction_type' => $transactionType,
        ]);

        return $this->request('POST', '/v1/report/transactions/create', $query);
    }
}
